### ISSUE TITLE
Add blog article page

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#10]
Add blog article page to display article contents. Article source should come from Netlify CMS.

**Comment by Goolzzi** [comment]
@jgwerner What image should be placed in top section of page?
I think, it should be `postimage` in blog master page.
Please let me know.
Goolzzi

**Comment by jgwerner** [comment]
@Goolzzi not sure. we could not add a header image and just add the nav bar at the top. the article image should be enough. That would not be 100% inline with the design but could simplify matters for now.

What do you think?

**Comment by Goolzzi** [comment]
@jgwerner I think so.
Anyway, I will add article image at the header.
After then, let's talk about it again.

**Comment by jgwerner** [comment]
@Goolzzi ok sounds like a plan.
