### ISSUE TITLE
"Learn More" button on main page is not clickable (desktop and mobile)

### ISSUE THREAD

**Issue by nathanielcompton** [cupofdata/www-site#102]
I cannot press the "Learn More" button on either the desktop or mobile versions of the site.

![screen shot 2018-02-15 at 11 28 38 am](https://user-images.githubusercontent.com/12648281/36268073-972a59d2-1243-11e8-991f-169a5b66c001.png)

**Comment by Goolzzi** [comment]
@jgwerner what is your desired action for this button?

**Comment by jgwerner** [comment]
@Goolzzi Eventually to go to the features page. Since we don't have a features page, we could just remove it for now.
