### ISSUE TITLE
Are "Contact Us" social media links providing right functionality?

### ISSUE THREAD

**Issue by nathanielcompton** [cupofdata/www-site#104]
Reference video available via: https://imgur.com/a/GQKqc

We have three clickable social media icons under the "Contact Us" portion of the site.

When clicking on these icons, they open a new window to "share" our website, instead of providing a link to directly contact the company. Is this functionality correct?

**Comment by jgwerner** [comment]
@nathanielcompton it's not. It should be to contact the company. Will update.

**Comment by jgwerner** [comment]
@Goolzzi could you replace the share option and open the social pages instead? The links to the social media pages are o.k.

```
import {
	FacebookShareButton,
	LinkedinShareButton,
	TwitterShareButton,
} from 'react-share'
import {
	LINKEDIN_URL,
	FACEBOOK_URL,
	TWITTER_URL,
	SOCIAL_TITLE
```

**Comment by Goolzzi** [comment]
No problem
