### ISSUE TITLE
Add Pricing page

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#11]
Add standard pricing page. Should include a section with Frequently Asked Questions (FAQs) related to pricing.

**Comment by jgwerner** [comment]
@sumitrk here is some additional information for the pricing page. I think the first version could be very simple, like so:

- Starter / 689 USD per month
-- 1000 validated contacts

- Pro / 1250 USD per month
-- 2000 validated contacts

- Enterprise / Call Us
-- Unlimited contacts

Additional notes: 

- Toggle between annual and monthly pricing.
- Annual pricing would have a 20% discount, since its prepaid.
- We should add a FAQs section below the pricing table. Eventually, we could have the CMS integrated to update that content.
- The layout for pricing should have a cards format and have a CTA within the card for a free registration.

/cc @Goolzzi

**Comment by jgwerner** [comment]
@sumitrk we should have the option to add text within the cards, such as features. For the design, you could add three bullets to each option as place holders.

**Comment by Goolzzi** [comment]
![screen shot 2018-02-14 at 11 49 22 am](https://user-images.githubusercontent.com/25907048/36224677-28669aea-117d-11e8-9f99-119a41f83a1e.png)

@jgwerner how should I dispose plan mode(Monthly, yearly) button in mobile version?
And I assume there will be some feedback something like that **the content price plan card need to be changed by plan mode.**

Please let me get your feedback for this page

**Comment by jgwerner** [comment]
@Goolzzi perhaps we could avoid the toggle altogether and add a banner stating that the user could get two months free by signing up for the yearly plan. Thoughts?

![screen shot 2018-02-14 at 3 19 25 pm](https://user-images.githubusercontent.com/920170/36226018-98fd3198-119a-11e8-8aa0-a7c31169b47c.png)

**Comment by jgwerner** [comment]
@Goolzzi FAQs:

What forms of payment do you accept?

Thanks to the good people at Stripe, we accept all major credit cards. We also accept wire transfers and electronic checks. 

How is your service different from all other B2B lead gen service out there?

Cup of Data uses Machine Learning and Deep Learning to identify the best leads, for you. The models improve over time by tracking attributes and conversions that lead to successful engagements and sales. So it's more than just B2B lead gen, it's your own personal an automated sales coach! 

Do you leverage third-party databases?

Absolutely. We rely on firmographic, technographic, social, and public data and in many cases, these data sources have costs and long-term commitments.

Do you integrate with CRM and Martech solutions?

You bet. We designed Cup of Data from the get-go to integrate with any solution. 

Do you offer free trials for your service?

We do for a limited number of accounts and validated contacts. Cup of Data works best once our A.I. models track milestones, starting with conversions, and create challenger models to improve outcomes. If you would like a demo, you can schedule one [here](https://cupofdata.com/onboard/).

Do you augment account and contact lists with context?

Yes. If you can engage the customer with the right message, at the right time, and in the right format you will have a big advantage. Context helps accomplish that.
