### ISSUE TITLE
Update website banner

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#135]
Update website hero banner with the latest version.

**Comment by jgwerner** [comment]
There are two versions, we should start with the version that has the quality score indicator over the persona.

**Comment by Goolzzi** [comment]
@jgwerner Could you please share the video link of tutorial?

**Comment by jgwerner** [comment]
@Goolzzi We don't have it yet. It will arrive in about a week. So we can just leave the design as is and change the banner, only.

**Comment by jgwerner** [comment]
@Goolzzi both regular and mobile banners are in Figma. Let's start with the one that has the score above the persona.
