### ISSUE TITLE
Correct job titles

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#45]
Correct job titles.

**Comment by Goolzzi** [comment]
IMO, if `OUR TEAM` is changed other word like `TEAM MEMBERS`, it would be fine to improve the page.
Btw, to have two `OUR TEAM` on a page as a title looks like awkward for this page.

**Comment by Goolzzi** [comment]
IMO, it would be better for us, if the topic is `what we do?` and member section title is 'OUR TEAM` or `TEAM MEMBERS`

That's only my suggestion. All things up to on your mind.
If you don't like my suggestion, pls ignore it.
