### ISSUE TITLE
Allow news home page edits from Netlify CMS

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#80]
News texts are hardcoded. Update so users can update the text with Netlify's CMS.

If there are more than three, then take the last three entries and add those to the home page.

**Comment by Goolzzi** [comment]
@jgwerner By fixing this issue, we can show one or more articles on the news page.
Do you still want to keep only one news in the news section of the homepage?

**Comment by jgwerner** [comment]
@Goolzzi eventually we can add more than one article. However, as of this writing, we only have one news article to show.

**Comment by Goolzzi** [comment]
Ok, I see
