### ISSUE TITLE
Manage onboarding links as environment variables

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#94]
Refactor codebase so we can manage environment variables for onboarding links.

These are used for A/B testing and as such we would like to update them directly within Netlify (or any other hoster) without having to change the code base.

Onboarding URL is currently located in `src/pages/onboard.js`.

**Comment by Goolzzi** [comment]
https://github.com/cupofdata/www-site/blob/0eb65ee371c0a3e782e03d715556cf3d362c8685/gatsby-config.js#L2

What do you think to set env variable in `gatsby-config.js`.

**Comment by jgwerner** [comment]
@Goolzzi I was thinking more of [environment variables](https://www.gatsbyjs.org/docs/environment-variables/), which would allow us to change the value [within Netlify](https://www.netlify.com/docs/continuous-deployment/) without having to modify any code.
