### ISSUE TITLE
Onboard path does not refresh

### ISSUE THREAD

**Issue by jgwerner** [cupofdata/www-site#96]
The onboard path works with the new env var setting, however, it does not load correctly when the user refreshes the page.

**Comment by Goolzzi** [comment]
I can't find any problem. It is working well on my end.
Could you please write more detailed case step by step, so I can track and sort the bugs?

**Comment by jgwerner** [comment]
@Goolzzi it seems to be an issue related to iPhones with Safari. The page loads correctly now, however, the icons are out of place with the iPhone/Safari upon refresh. I disabled the A/B test in Netlify and that seemed to help.

We can put this bug on-hold right now since its not high priority.

**Comment by jgwerner** [comment]
No longer applicable.
